### ISSUE TITLE
UnhandledRejection: Error: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by jantimon** [credred/karma-vite#2]
From time to time I get an error `UnhandledRejection: Error: Cannot set headers after they are sent to the client`.

```
ERROR [karma-server]: UnhandledRejection: Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:603:11)
    at node_modules/karma-vite/dist/index.js:144:19
```

The best way to reproduce it is adding https://www.npmjs.com/package/karma-parallel - in that case it is happening for every test run for me.

Maybe a fix could be:

```js
try {
  res.setHeader("Content-Type", "application/javascript");
} catch (e) {}
```

**Comment by credred** [comment]
Although I didn't reproduce it, I think I found the reason. This problem has been fixed

**Comment by jantimon** [comment]
Thank you so much 👍
